# Generated by Django 5.0.7 on 2024-07-11 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('data science', 'data science'), ('web development', 'web development'), ('AI', 'AI')], max_length=20)),
                ('reasons', models.CharField(choices=[('for fun', 'for fun'), ('for study', 'for study'), ('career advancement', 'career advancement'), ('career change', 'career change')], max_length=20)),
                ('start_level', models.CharField(choices=[('total beginner', 'total beginner'), ('high beginner', 'high beginner'), ('intermediate', 'intermediate'), ('high intermediate', 'high intermediate'), ('expert', 'expert')], max_length=20)),
                ('goals', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('weakness', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
