# Generated by Django 5.0.7 on 2024-07-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='user',
            new_name='user_name',
        ),
    ]
